name: PCA UI www CD

on:
  push:
    tags: 
      - "testing-*.*.*"

#oidc encima de oauth 2.0
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: 'npm'

    #   - name: install
    #     run: npm i
    #     working-directory: ./pca-ui/src/www

    #   - name: Run unit tests
    #     run: npm t
    #     working-directory: ./pca-ui/src/www

    #   - name: compile dist
    #     run: CI=false npm run build
    #     working-directory: ./pca-ui/src/www

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::147997163080:role/GithubActionsS3Role
          role-session-name: GithubSessionTesting # OIDC

      - name: Check login
        run: aws sts get-caller-identity

      - name: Generate version file
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Write version file
        run: echo "{ \"name\"":" \"Evoltis PCA\", \"version\"":" \""${{  github.ref_name }}"\", \"publishDate\"":"\""$NOW"\"}" >> ./pca-ui/src/www/build/version.json

      - name: Upload to S3
        run: aws s3 sync ./pca-ui/src/www/build s3://evatesting-pcaui-1kaqct739gwls-web-swdh3-webbucket-qsmadvlynpla --delete --exclude "config.js"

      - name: Create Cloudfront invalidation
        run: aws cloudfront create-invalidation --distribution-id E15LAU1V49TSVL --paths "/index.html" "/version.json"
